# Generated by Django 5.1.3 on 2025-03-05 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التحقق"),
                ),
                ("is_valid", models.BooleanField(verbose_name="صالح")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("AUTO", "تلقائي عند التنزيل"),
                            ("MANUAL", "يدوي عبر الواجهة"),
                            ("API", "طلب API"),
                            ("CLI", "أمر سطر الأوامر"),
                        ],
                        default="AUTO",
                        max_length=10,
                        verbose_name="طريقة التحقق",
                    ),
                ),
                (
                    "error_details",
                    models.TextField(blank=True, verbose_name="تفاصيل الخطأ"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                        verbose_name="المستند",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التحقق بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل التحقق",
                "verbose_name_plural": "سجلات التحقق",
                "ordering": ["-verified_at"],
            },
        ),
    ]
